### ISSUE TITLE
Convert the .ai to svg logo

### ISSUE THREAD

**Issue by invisal** [invisal/khmercoders#4]
Convert the .ai logo to .svg and put it as logo for our top navigation

[khmercoders.zip](https://github.com/invisal/khmercoders/files/14236310/khmercoders.zip)

**Comment by Kimthean** [comment]
I've add khmercoder log and replace the old logo in the navbar

<img width="1791" alt="image" src="https://github.com/invisal/khmercoders/assets/124693005/db866a37-5230-499d-9fbf-7d266e6ba248">
