### ISSUE TITLE
refactor : database to support oauth2

### ISSUE THREAD

**Issue by avevotsira** [invisal/khmercoders#51]
In the future , we will have multiple provider , we should refactor our database to accommodate those requirement

**Comment by rin-yato** [comment]
u mean how db now cant support that? i think it does

**Comment by avevotsira** [comment]
> u mean how db now cant support that? i think it does

it supported right now but i believe we don't store the context of the the provider, for example github , normally i store the provider id as well.

**Comment by rin-yato** [comment]
can you check the user_key table?
