### ISSUE TITLE
bug: Error message in sign in page does not look good with dark mode.

### ISSUE THREAD

**Issue by soknaly** [invisal/khmercoders#7]
### Description

Error message in sign in page does not look good with dark mode.

### Steps to Reproduce

- Simply go to the sign-in page
- Type the incorrect information to get the error
- You will see an error message.

### Screenshots

![image](https://github.com/invisal/khmercoders/assets/20983608/d49d7f74-ef92-4948-bd53-4259729ad8a3)

**Comment by rin-yato** [comment]
@avevotsira @Kimthean @Sliden101

**Comment by Sliden101** [comment]
Picking this up

**Comment by rin-yato** [comment]
I think @Sliden101 pushed this one already, closed by [fix: error message ugly](https://github.com/invisal/khmercoders/commit/4ade9c5dad720f5989e3f0c0af01cc00d681681f)
